# Generated by Django 2.2.6 on 2019-10-28 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookDistributors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('earnings', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CookBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bookdistributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipebox.BookDistributors')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('recipe', models.TextField()),
                ('cookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipebox.CookBook')),
            ],
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='NewsItem',
        ),
    ]
