# Generated by Django 2.2.6 on 2019-10-28 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0002_auto_20191028_2032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookDistributors',
            new_name='BookDistributor',
        ),
        migrations.RenameModel(
            old_name='Recipes',
            new_name='Recipe',
        ),
    ]
